### PR TITLE
fix: adjust liboqs pkgconfig version detection to new scheme

### PR DESCRIPTION
**Pull request by tranzystorek-io**
Noticed this part wasn't touched after the versioning update, this works correctly with it.

### CODE REVIEW

**Review by thomwiggers — APPROVED** [review]

**Comment by thomwiggers** [comment]
Do we need to do a patch release for this or are we good?

Relatedly I'm thinking we should probably split out the vendored stuff in its own crate, because I suppose we might want to separately bump `oqs`, `oqs-sys`'s minimum requirement and the default-included code...

**Comment by tranzystorek-io** [comment]
The old code tries to match pkgconfig with a nonsense version range, which doesn't break anything AFAIU, but also plain doesn't work as intended, so a patch seems desirable.

As for your second point, I'm not sure I follow, or maybe I don't see the benefit of separating the vendored code.

**Comment by thomwiggers** [comment]
Imagine liboqs publishes version `0.9.1`, then I would like to package `oqs-sys` version `0.9.x+liboqs-0.9.1`. But that would also bump the minimum requirement for `pkgconfig` even if it should still be compatible with liboqs `0.9.0`. 

Moving the vendored code into a separate crate would allow Cargo's dependency resolver to resolve such conflicts. I suppose that alternatively we could get rid of the version autodetection but that means we have yet another version code point to keep track of when updating...

**Comment by tranzystorek-io** [comment]
> But that would also bump the minimum requirement for `pkgconfig` even if it should still be compatible with liboqs `0.9.0`.

Huh, I haven't thought about that, but my reasoning was if we declare liboqs-0.9.1 we should vendor or accept via pkgconfig only versions that include at least fixes from that baseline version, so patch numbers `>=1`.

**Comment by thomwiggers** [comment]
Patch releases could also include improvements, such as new implementations, though. It's a bit tricky.

Anyway I don't care about this _too_ much, we'll see if the OS vendors yell at us down the line.

**Comment by tranzystorek-io** [comment]
Looks like 0.9.1 wasn't released on crates.io, presumably a simple omission?

**Pull request merged**
